name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: 'testuser'
          mysql password: testpassword
          mysql root password: root
          mysql database: 'bussin'
      - name: Build with Maven
        env:
          COGNITO_PASSWORD: ${{secrets.COGNITO_PASSWORD}}
          COGNITO_USERNAME: ${{secrets.COGNITO_USERNAME}}
          COGNITO_DRIVERNAME: ${{secrets.COGNITO_DRIVERNAME}}
          CLIENTID: ${{secrets.CLIENTID}}
          ENDPOINT: ${{secrets.ENDPOINT}}
          REGION: ${{secrets.REGION}}
          USERPOOLID: ${{secrets.USERPOOLID}}
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        run: |
          mvn clean install
      - name: Coveralls Coverage Report Submission
        run: mvn coveralls:report --define repoToken=${{ secrets.COVERALL_REPO_TOKEN }}
